routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'Auth\LoginController@showLoginForm');
Auth::Routes();
Route::group(['middleware' => 'auth'], function () {
    Route::get('/home', 'HomeController@index')->name('home');
    Route::resource('clientes', 'ClienteController');
    Route::resource('infoClientes', 'InfoClienteController');
    Route::resource('central_users', 'CentralUserController');
    Route::resource('logs', 'LogController');
    Route::resource('permisos', 'PermisoController');
    Route::resource('roles', 'RolesController');
    Route::resource('marcas', 'MarcasController');
    Route::resource('orgs', 'OrgController');
    Route::resource('estacionamientos', 'EstacionamientoController');
    Route::resource('tipoTickets', 'TipoTicketController');
    Route::resource('tickets', 'TicketController');
    Route::resource('factura', 'FacturaController');
    Route::resource('tipoPagos', 'TipoPagoController');
    Route::resource('tipoPensions', 'TipoPensionController');
    Route::resource('formaPagos', 'FormaPagoController');
    Route::resource('imgIngresos', 'ImgIngresoController');
    Route::resource('ingresos', 'IngresoController');
    Route::resource('bancoCollects', 'BancoCollectController');
    Route::resource('empresaCollects', 'EmpresaCollectController');
    Route::resource('gerentes', 'GerenteController');
    Route::resource('dashboard', 'DashboardController');
    Route::resource('diarioingreso', 'DiarioIngresoController');
    Route::resource('firmas', 'FirmaController');
    Route::get('/xml/{id}', 'FacturaController@downloadXML')->name('xml');
    Route::get('/pdf/{id}', 'FacturaController@downloadPDF')->name('pdf');
    Route::get('/img/{id}', 'TicketController@DownImg')->name('img');
    Route::post('/generar/', 'FacturaController@create')->name('generar');
    Route::post('/buscar/facturas','FacturaController@busqueda')->name('busqueda');
    Route::post('/email', 'FacturaController@enviarEmail')->name('email');
    Route::post('/actualiza/{id}', 'TicketController@actualiza')->name('no_est');
    Route::post('/tickets/timbrado/', 'FacturaController@timbrado')->name('timbrar');
    Route::get('/tickets/validar/{id}', 'TicketController@valido')->name('valido');
    Route::post('/tickets/rechazo/{id}', 'TicketController@rechazo')->name('rechazo');
    Route::get('/rechazados', 'TicketController@list_rechazo')->name('list_rechazo');
    Route::post('dashboard', 'DashboardController@AjaxRequest')->name('dashboard');
    Route::get('/graficas/{id}', 'EstacionamientoController@graficas')->name('graficas');
    Route::get('/ingresos/rechazados', 'IngresoController@Frechazos')->name('ingresos.rechazo');
    Route::get('/facturas/pi','FacturaController@pi')->name('pi');
    Route::get('/orgs/cambio/{id}','OrgController@cambio')->name('cambio');
    Route::get('/fichas/validar/{id}', 'IngresoController@Fvalidos')->name('valido_ficha');
    Route::post('/fichas/rechazo/{id}', 'IngresoController@Frechazos')->name('rechazo_ficha');
    Route::get('/calendario','IngresoController@calendario')->name('calendar');
});



Route::resource('pagos', 'PagoController');
Route::resource('operacionDiarias', 'OperacionDiariaController');
Route::resource('pensions', 'PensionController');


Route::resource('operacionDiarias', 'OperacionDiariaController');

Route::resource('facturaPensions', 'FacturaPensionController');

app/Models/BancoCollect.php
<?php

namespace App\Models;

use Eloquent as Model;
use Illuminate\Database\Eloquent\SoftDeletes;

/**
 * Class BancoCollect
 * @package App\Models
 * @version September 19, 2019, 7:26 pm UTC
 *
 * @property \Illuminate\Database\Eloquent\Collection ingresos
 * @property string banco
 */
class BancoCollect extends Model
{
    use SoftDeletes;

    public $table = 'banco_colect';
    
    const CREATED_AT = 'created_at';
    const UPDATED_AT = 'updated_at';


    protected $dates = ['deleted_at'];


    public $fillable = [
        'banco'
    ];

    /**
     * The attributes that should be casted to native types.
     *
     * @var array
     */
    protected $casts = [
        'id' => 'integer',
        'banco' => 'string'
    ];

    /**
     * Validation rules
     *
     * @var array
     */
    public static $rules = [
        'banco' => 'required'
    ];

    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     **/
    public function ingresos()
    {
        return $this->hasMany(\App\Models\Ingreso::class, 'id_banco');
    }
}

app/Http/Controllers/BancoCollectController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\CreateBancoCollectRequest;
use App\Http\Requests\UpdateBancoCollectRequest;
use App\Repositories\BancoCollectRepository;
use App\Http\Controllers\AppBaseController;
use Illuminate\Http\Request;
use Flash;
use Response;

class BancoCollectController extends AppBaseController
{
    /** @var  BancoCollectRepository */
    private $bancoCollectRepository;

    public function __construct(BancoCollectRepository $bancoCollectRepo)
    {
        $this->bancoCollectRepository = $bancoCollectRepo;
    }

    /**
     * Display a listing of the BancoCollect.
     *
     * @param Request $request
     *
     * @return Response
     */
    public function index(Request $request)
    {
        $bancoCollects = $this->bancoCollectRepository->all();

        return view('banco_collects.index')
            ->with('bancoCollects', $bancoCollects);
    }

    /**
     * Show the form for creating a new BancoCollect.
     *
     * @return Response
     */
    public function create()
    {
        return view('banco_collects.create');
    }

    /**
     * Store a newly created BancoCollect in storage.
     *
     * @param CreateBancoCollectRequest $request
     *
     * @return Response
     */
    public function store(CreateBancoCollectRequest $request)
    {
        $input = $request->all();

        $bancoCollect = $this->bancoCollectRepository->create($input);

        Flash::success('Banco Collect saved successfully.');

        return redirect(route('bancoCollects.index'));
    }

    /**
     * Display the specified BancoCollect.
     *
     * @param int $id
     *
     * @return Response
     */
    public function show($id)
    {
        $bancoCollect = $this->bancoCollectRepository->find($id);

        if (empty($bancoCollect)) {
            Flash::error('Banco Collect not found');

            return redirect(route('bancoCollects.index'));
        }

        return view('banco_collects.show')->with('bancoCollect', $bancoCollect);
    }

    /**
     * Show the form for editing the specified BancoCollect.
     *
     * @param int $id
     *
     * @return Response
     */
    public function edit($id)
    {
        $bancoCollect = $this->bancoCollectRepository->find($id);

        if (empty($bancoCollect)) {
            Flash::error('Banco Collect not found');

            return redirect(route('bancoCollects.index'));
        }

        return view('banco_collects.edit')->with('bancoCollect', $bancoCollect);
    }

    /**
     * Update the specified BancoCollect in storage.
     *
     * @param int $id
     * @param UpdateBancoCollectRequest $request
     *
     * @return Response
     */
    public function update($id, UpdateBancoCollectRequest $request)
    {
        $bancoCollect = $this->bancoCollectRepository->find($id);

        if (empty($bancoCollect)) {
            Flash::error('Banco Collect not found');

            return redirect(route('bancoCollects.index'));
        }

        $bancoCollect = $this->bancoCollectRepository->update($request->all(), $id);

        Flash::success('Banco Collect updated successfully.');

        return redirect(route('bancoCollects.index'));
    }

    /**
     * Remove the specified BancoCollect from storage.
     *
     * @param int $id
     *
     * @throws \Exception
     *
     * @return Response
     */
    public function destroy($id)
    {
        $bancoCollect = $this->bancoCollectRepository->find($id);

        if (empty($bancoCollect)) {
            Flash::error('Banco Collect not found');

            return redirect(route('bancoCollects.index'));
        }

        $this->bancoCollectRepository->delete($id);

        Flash::success('Banco Collect deleted successfully.');

        return redirect(route('bancoCollects.index'));
    }
}

resources/views/banco_collects/create.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Banco Collect
        </h1>
    </section>
    <div class="content">
        @include('adminlte-templates::common.errors')
        <div class="box box-primary">

            <div class="box-body">
                <div class="row">
                    {!! Form::open(['route' => 'bancoCollects.store']) !!}

                        @include('banco_collects.fields')

                    {!! Form::close() !!}
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/banco_collects/edit.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Banco Collect
        </h1>
   </section>
   <div class="content">
       @include('adminlte-templates::common.errors')
       <div class="box box-primary">
           <div class="box-body">
               <div class="row">
                   {!! Form::model($bancoCollect, ['route' => ['bancoCollects.update', $bancoCollect->id], 'method' => 'patch']) !!}

                        @include('banco_collects.fields')

                   {!! Form::close() !!}
               </div>
           </div>
       </div>
   </div>
@endsection

resources/views/banco_collects/fields.blade.php
<!-- Banco Field -->
<div class="form-group col-sm-6">
    {!! Form::label('banco', 'Banco:') !!}
    {!! Form::text('banco', null, ['class' => 'form-control']) !!}
</div>

<!-- Submit Field -->
<div class="form-group col-sm-12">
    {!! Form::submit('Save', ['class' => 'btn btn-primary']) !!}
    <a href="{!! route('bancoCollects.index') !!}" class="btn btn-default">Cancel</a>
</div>

resources/views/banco_collects/index.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1 class="pull-left">Banco Collects</h1>
        <h1 class="pull-right">
           <a class="btn btn-primary pull-right" style="margin-top: -10px;margin-bottom: 5px" href="{!! route('bancoCollects.create') !!}">Add New</a>
        </h1>
    </section>
    <div class="content">
        <div class="clearfix"></div>

        @include('flash::message')

        <div class="clearfix"></div>
        <div class="box box-primary">
            <div class="box-body">
                    @include('banco_collects.table')
            </div>
        </div>
        <div class="text-center">
        
        </div>
    </div>
@endsection

resources/views/banco_collects/show.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Banco Collect
        </h1>
    </section>
    <div class="content">
        <div class="box box-primary">
            <div class="box-body">
                <div class="row" style="padding-left: 20px">
                    @include('banco_collects.show_fields')
                    <a href="{!! route('bancoCollects.index') !!}" class="btn btn-default">Back</a>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/banco_collects/show_fields.blade.php
<!-- Id Field -->
<div class="form-group">
    {!! Form::label('id', 'Id:') !!}
    <p>{!! $bancoCollect->id !!}</p>
</div>

<!-- Banco Field -->
<div class="form-group">
    {!! Form::label('banco', 'Banco:') !!}
    <p>{!! $bancoCollect->banco !!}</p>
</div>

<!-- Created At Field -->
<div class="form-group">
    {!! Form::label('created_at', 'Created At:') !!}
    <p>{!! $bancoCollect->created_at !!}</p>
</div>

<!-- Updated At Field -->
<div class="form-group">
    {!! Form::label('updated_at', 'Updated At:') !!}
    <p>{!! $bancoCollect->updated_at !!}</p>
</div>

<!-- Deleted At Field -->
<div class="form-group">
    {!! Form::label('deleted_at', 'Deleted At:') !!}
    <p>{!! $bancoCollect->deleted_at !!}</p>
</div>

resources/views/banco_collects/table.blade.php
<div class="table-responsive">
    <table class="table" id="bancoCollects-table">
        <thead>
            <tr>
                <th>Banco</th>
                <th colspan="3">Action</th>
            </tr>
        </thead>
        <tbody>
        @foreach($bancoCollects as $bancoCollect)
            <tr>
                <td>{!! $bancoCollect->banco !!}</td>
                <td>
                    {!! Form::open(['route' => ['bancoCollects.destroy', $bancoCollect->id], 'method' => 'delete']) !!}
                    <div class='btn-group'>
                        <a href="{!! route('bancoCollects.show', [$bancoCollect->id]) !!}" class='btn btn-default btn-xs'><i class="glyphicon glyphicon-eye-open"></i></a>
                        <a href="{!! route('bancoCollects.edit', [$bancoCollect->id]) !!}" class='btn btn-default btn-xs'><i class="glyphicon glyphicon-edit"></i></a>
                        {!! Form::button('<i class="glyphicon glyphicon-trash"></i>', ['type' => 'submit', 'class' => 'btn btn-danger btn-xs', 'onclick' => "return confirm('Are you sure?')"]) !!}
                    </div>
                    {!! Form::close() !!}
                </td>
            </tr>
        @endforeach
        </tbody>
    </table>
</div>