routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'Auth\LoginController@showLoginForm');
Auth::Routes();
Route::group(['middleware' => 'auth'], function () {
    Route::get('/home', 'HomeController@index')->name('home');
    Route::resource('clientes', 'ClienteController');
    Route::resource('infoClientes', 'InfoClienteController');
    Route::resource('central_users', 'CentralUserController');
    Route::resource('logs', 'LogController');
    Route::resource('permisos', 'PermisoController');
    Route::resource('roles', 'RolesController');
    Route::resource('marcas', 'MarcasController');
    Route::resource('orgs', 'OrgController');
    Route::resource('estacionamientos', 'EstacionamientoController');
    Route::resource('tipoTickets', 'TipoTicketController');
    Route::resource('tickets', 'TicketController');
    Route::resource('factura', 'FacturaController');
    Route::resource('tipoPagos', 'TipoPagoController');
    Route::resource('tipoPensions', 'TipoPensionController');
    Route::resource('formaPagos', 'FormaPagoController');
    Route::resource('imgIngresos', 'ImgIngresoController');
    Route::resource('ingresos', 'IngresoController');
    Route::resource('bancoCollects', 'BancoCollectController');
    Route::resource('empresaCollects', 'EmpresaCollectController');
    Route::resource('gerentes', 'GerenteController');
    Route::resource('dashboard', 'DashboardController');
    Route::resource('diarioingreso', 'DiarioIngresoController');
    Route::resource('firmas', 'FirmaController');
    Route::get('/xml/{id}', 'FacturaController@downloadXML')->name('xml');
    Route::get('/pdf/{id}', 'FacturaController@downloadPDF')->name('pdf');
    Route::get('/img/{id}', 'TicketController@DownImg')->name('img');
    Route::post('/generar/', 'FacturaController@create')->name('generar');
    Route::post('/buscar/facturas','FacturaController@busqueda')->name('busqueda');
    Route::post('/email', 'FacturaController@enviarEmail')->name('email');
    Route::post('/actualiza/{id}', 'TicketController@actualiza')->name('no_est');
    Route::post('/tickets/timbrado/', 'FacturaController@timbrado')->name('timbrar');
    Route::get('/tickets/validar/{id}', 'TicketController@valido')->name('valido');
    Route::post('/tickets/rechazo/{id}', 'TicketController@rechazo')->name('rechazo');
    Route::get('/rechazados', 'TicketController@list_rechazo')->name('list_rechazo');
    Route::post('dashboard', 'DashboardController@AjaxRequest')->name('dashboard');
    Route::get('/graficas/{id}', 'EstacionamientoController@graficas')->name('graficas');
    Route::get('/ingresos/rechazados', 'IngresoController@Frechazos')->name('ingresos.rechazo');
    Route::get('/facturas/pi','FacturaController@pi')->name('pi');
    Route::get('/orgs/cambio/{id}','OrgController@cambio')->name('cambio');
    Route::get('/fichas/validar/{id}', 'IngresoController@Fvalidos')->name('valido_ficha');
    Route::post('/fichas/rechazo/{id}', 'IngresoController@Frechazos')->name('rechazo_ficha');
    Route::get('/calendario','IngresoController@calendario')->name('calendar');
});



Route::resource('pagos', 'PagoController');
Route::resource('operacionDiarias', 'OperacionDiariaController');
Route::resource('pensions', 'PensionController');


Route::resource('operacionDiarias', 'OperacionDiariaController');

Route::resource('facturaPensions', 'FacturaPensionController');

app/Models/EmpresaCollect.php
<?php

namespace App\Models;

use Eloquent as Model;
use Illuminate\Database\Eloquent\SoftDeletes;

/**
 * Class EmpresaCollect
 * @package App\Models
 * @version September 19, 2019, 7:27 pm UTC
 *
 * @property \Illuminate\Database\Eloquent\Collection ingresos
 * @property string empresa
 */
class EmpresaCollect extends Model
{
    use SoftDeletes;

    public $table = 'empresa_colect';
    
    const CREATED_AT = 'created_at';
    const UPDATED_AT = 'updated_at';


    protected $dates = ['deleted_at'];


    public $fillable = [
        'empresa'
    ];

    /**
     * The attributes that should be casted to native types.
     *
     * @var array
     */
    protected $casts = [
        'id' => 'integer',
        'empresa' => 'string'
    ];

    /**
     * Validation rules
     *
     * @var array
     */
    public static $rules = [
        'empresa' => 'required'
    ];

    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     **/
    public function ingresos()
    {
        return $this->hasMany(\App\Models\Ingreso::class, 'id_empresa');
    }
}

app/Http/Controllers/EmpresaCollectController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\CreateEmpresaCollectRequest;
use App\Http\Requests\UpdateEmpresaCollectRequest;
use App\Repositories\EmpresaCollectRepository;
use App\Http\Controllers\AppBaseController;
use Illuminate\Http\Request;
use Flash;
use Response;

class EmpresaCollectController extends AppBaseController
{
    /** @var  EmpresaCollectRepository */
    private $empresaCollectRepository;

    public function __construct(EmpresaCollectRepository $empresaCollectRepo)
    {
        $this->empresaCollectRepository = $empresaCollectRepo;
    }

    /**
     * Display a listing of the EmpresaCollect.
     *
     * @param Request $request
     *
     * @return Response
     */
    public function index(Request $request)
    {
        $empresaCollects = $this->empresaCollectRepository->all();

        return view('empresa_collects.index')
            ->with('empresaCollects', $empresaCollects);
    }

    /**
     * Show the form for creating a new EmpresaCollect.
     *
     * @return Response
     */
    public function create()
    {
        return view('empresa_collects.create');
    }

    /**
     * Store a newly created EmpresaCollect in storage.
     *
     * @param CreateEmpresaCollectRequest $request
     *
     * @return Response
     */
    public function store(CreateEmpresaCollectRequest $request)
    {
        $input = $request->all();

        $empresaCollect = $this->empresaCollectRepository->create($input);

        Flash::success('Empresa Collect saved successfully.');

        return redirect(route('empresaCollects.index'));
    }

    /**
     * Display the specified EmpresaCollect.
     *
     * @param int $id
     *
     * @return Response
     */
    public function show($id)
    {
        $empresaCollect = $this->empresaCollectRepository->find($id);

        if (empty($empresaCollect)) {
            Flash::error('Empresa Collect not found');

            return redirect(route('empresaCollects.index'));
        }

        return view('empresa_collects.show')->with('empresaCollect', $empresaCollect);
    }

    /**
     * Show the form for editing the specified EmpresaCollect.
     *
     * @param int $id
     *
     * @return Response
     */
    public function edit($id)
    {
        $empresaCollect = $this->empresaCollectRepository->find($id);

        if (empty($empresaCollect)) {
            Flash::error('Empresa Collect not found');

            return redirect(route('empresaCollects.index'));
        }

        return view('empresa_collects.edit')->with('empresaCollect', $empresaCollect);
    }

    /**
     * Update the specified EmpresaCollect in storage.
     *
     * @param int $id
     * @param UpdateEmpresaCollectRequest $request
     *
     * @return Response
     */
    public function update($id, UpdateEmpresaCollectRequest $request)
    {
        $empresaCollect = $this->empresaCollectRepository->find($id);

        if (empty($empresaCollect)) {
            Flash::error('Empresa Collect not found');

            return redirect(route('empresaCollects.index'));
        }

        $empresaCollect = $this->empresaCollectRepository->update($request->all(), $id);

        Flash::success('Empresa Collect updated successfully.');

        return redirect(route('empresaCollects.index'));
    }

    /**
     * Remove the specified EmpresaCollect from storage.
     *
     * @param int $id
     *
     * @throws \Exception
     *
     * @return Response
     */
    public function destroy($id)
    {
        $empresaCollect = $this->empresaCollectRepository->find($id);

        if (empty($empresaCollect)) {
            Flash::error('Empresa Collect not found');

            return redirect(route('empresaCollects.index'));
        }

        $this->empresaCollectRepository->delete($id);

        Flash::success('Empresa Collect deleted successfully.');

        return redirect(route('empresaCollects.index'));
    }
}

resources/views/empresa_collects/create.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Empresa Collect
        </h1>
    </section>
    <div class="content">
        @include('adminlte-templates::common.errors')
        <div class="box box-primary">

            <div class="box-body">
                <div class="row">
                    {!! Form::open(['route' => 'empresaCollects.store']) !!}

                        @include('empresa_collects.fields')

                    {!! Form::close() !!}
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/empresa_collects/edit.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Empresa Collect
        </h1>
   </section>
   <div class="content">
       @include('adminlte-templates::common.errors')
       <div class="box box-primary">
           <div class="box-body">
               <div class="row">
                   {!! Form::model($empresaCollect, ['route' => ['empresaCollects.update', $empresaCollect->id], 'method' => 'patch']) !!}

                        @include('empresa_collects.fields')

                   {!! Form::close() !!}
               </div>
           </div>
       </div>
   </div>
@endsection

resources/views/empresa_collects/fields.blade.php
<!-- Empresa Field -->
<div class="form-group col-sm-6">
    {!! Form::label('empresa', 'Empresa:') !!}
    {!! Form::text('empresa', null, ['class' => 'form-control']) !!}
</div>

<!-- Submit Field -->
<div class="form-group col-sm-12">
    {!! Form::submit('Save', ['class' => 'btn btn-primary']) !!}
    <a href="{!! route('empresaCollects.index') !!}" class="btn btn-default">Cancel</a>
</div>

resources/views/empresa_collects/index.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1 class="pull-left">Empresa Collects</h1>
        <h1 class="pull-right">
           <a class="btn btn-primary pull-right" style="margin-top: -10px;margin-bottom: 5px" href="{!! route('empresaCollects.create') !!}">Add New</a>
        </h1>
    </section>
    <div class="content">
        <div class="clearfix"></div>

        @include('flash::message')

        <div class="clearfix"></div>
        <div class="box box-primary">
            <div class="box-body">
                    @include('empresa_collects.table')
            </div>
        </div>
        <div class="text-center">
        
        </div>
    </div>
@endsection

resources/views/empresa_collects/show.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Empresa Collect
        </h1>
    </section>
    <div class="content">
        <div class="box box-primary">
            <div class="box-body">
                <div class="row" style="padding-left: 20px">
                    @include('empresa_collects.show_fields')
                    <a href="{!! route('empresaCollects.index') !!}" class="btn btn-default">Back</a>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/empresa_collects/show_fields.blade.php
<!-- Id Field -->
<div class="form-group">
    {!! Form::label('id', 'Id:') !!}
    <p>{!! $empresaCollect->id !!}</p>
</div>

<!-- Empresa Field -->
<div class="form-group">
    {!! Form::label('empresa', 'Empresa:') !!}
    <p>{!! $empresaCollect->empresa !!}</p>
</div>

<!-- Created At Field -->
<div class="form-group">
    {!! Form::label('created_at', 'Created At:') !!}
    <p>{!! $empresaCollect->created_at !!}</p>
</div>

<!-- Updated At Field -->
<div class="form-group">
    {!! Form::label('updated_at', 'Updated At:') !!}
    <p>{!! $empresaCollect->updated_at !!}</p>
</div>

<!-- Deleted At Field -->
<div class="form-group">
    {!! Form::label('deleted_at', 'Deleted At:') !!}
    <p>{!! $empresaCollect->deleted_at !!}</p>
</div>

resources/views/empresa_collects/table.blade.php
<div class="table-responsive">
    <table class="table" id="empresaCollects-table">
        <thead>
            <tr>
                <th>Empresa</th>
                <th colspan="3">Action</th>
            </tr>
        </thead>
        <tbody>
        @foreach($empresaCollects as $empresaCollect)
            <tr>
                <td>{!! $empresaCollect->empresa !!}</td>
                <td>
                    {!! Form::open(['route' => ['empresaCollects.destroy', $empresaCollect->id], 'method' => 'delete']) !!}
                    <div class='btn-group'>
                        <a href="{!! route('empresaCollects.show', [$empresaCollect->id]) !!}" class='btn btn-default btn-xs'><i class="glyphicon glyphicon-eye-open"></i></a>
                        <a href="{!! route('empresaCollects.edit', [$empresaCollect->id]) !!}" class='btn btn-default btn-xs'><i class="glyphicon glyphicon-edit"></i></a>
                        {!! Form::button('<i class="glyphicon glyphicon-trash"></i>', ['type' => 'submit', 'class' => 'btn btn-danger btn-xs', 'onclick' => "return confirm('Are you sure?')"]) !!}
                    </div>
                    {!! Form::close() !!}
                </td>
            </tr>
        @endforeach
        </tbody>
    </table>
</div>