routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'Auth\LoginController@showLoginForm');
Auth::Routes();
Route::group(['middleware' => 'auth'], function () {
    Route::get('/home', 'HomeController@index')->name('home');
    Route::resource('clientes', 'ClienteController');
    Route::resource('infoClientes', 'InfoClienteController');
    Route::resource('central_users', 'CentralUserController');
    Route::resource('logs', 'LogController');
    Route::resource('permisos', 'PermisoController');
    Route::resource('roles', 'RolesController');
    Route::resource('marcas', 'MarcasController');
    Route::resource('orgs', 'OrgController');
    Route::resource('estacionamientos', 'EstacionamientoController');
    Route::resource('tipoTickets', 'TipoTicketController');
    Route::resource('tickets', 'TicketController');
    Route::resource('factura', 'FacturaController');
    Route::resource('tipoPagos', 'TipoPagoController');
    Route::resource('tipoPensions', 'TipoPensionController');
    Route::resource('formaPagos', 'FormaPagoController');
    Route::resource('imgIngresos', 'ImgIngresoController');
    Route::resource('ingresos', 'IngresoController');
    Route::resource('bancoCollects', 'BancoCollectController');
    Route::resource('empresaCollects', 'EmpresaCollectController');
    Route::resource('gerentes', 'GerenteController');
    Route::resource('dashboard', 'DashboardController');
    Route::resource('diarioingreso', 'DiarioIngresoController');
    Route::resource('firmas', 'FirmaController');
    Route::get('/xml/{id}', 'FacturaController@downloadXML')->name('xml');
    Route::get('/pdf/{id}', 'FacturaController@downloadPDF')->name('pdf');
    Route::get('/img/{id}', 'TicketController@DownImg')->name('img');
    Route::post('/generar/', 'FacturaController@create')->name('generar');
    Route::post('/buscar/facturas','FacturaController@busqueda')->name('busqueda');
    Route::post('/email', 'FacturaController@enviarEmail')->name('email');
    Route::post('/actualiza/{id}', 'TicketController@actualiza')->name('no_est');
    Route::post('/tickets/timbrado/', 'FacturaController@timbrado')->name('timbrar');
    Route::get('/tickets/validar/{id}', 'TicketController@valido')->name('valido');
    Route::post('/tickets/rechazo/{id}', 'TicketController@rechazo')->name('rechazo');
    Route::get('/rechazados', 'TicketController@list_rechazo')->name('list_rechazo');
    Route::post('dashboard', 'DashboardController@AjaxRequest')->name('dashboard');
    Route::get('/graficas/{id}', 'EstacionamientoController@graficas')->name('graficas');
    Route::get('/ingresos/rechazados', 'IngresoController@Frechazos')->name('ingresos.rechazo');
    Route::get('/facturas/pi','FacturaController@pi')->name('pi');
    Route::get('/orgs/cambio/{id}','OrgController@cambio')->name('cambio');
    Route::get('/fichas/validar/{id}', 'IngresoController@Fvalidos')->name('valido_ficha');
    Route::post('/fichas/rechazo/{id}', 'IngresoController@Frechazos')->name('rechazo_ficha');
    Route::get('/calendario','IngresoController@calendario')->name('calendar');
});



Route::resource('pagos', 'PagoController');
Route::resource('operacionDiarias', 'OperacionDiariaController');
Route::resource('pensions', 'PensionController');


Route::resource('operacionDiarias', 'OperacionDiariaController');

Route::resource('facturaPensions', 'FacturaPensionController');

app/Models/FormaPago.php
<?php

namespace App\Models;

use Eloquent as Model;
use Illuminate\Database\Eloquent\SoftDeletes;

/**
 * Class FormaPago
 * @package App\Models
 * @version September 19, 2019, 5:24 pm UTC
 *
 * @property \Illuminate\Database\Eloquent\Collection pensions
 * @property string forma
 */
class FormaPago extends Model
{
    use SoftDeletes;

    public $table = 'forma_pago';
    
    const CREATED_AT = 'created_at';
    const UPDATED_AT = 'updated_at';


    protected $dates = ['deleted_at'];


    public $fillable = [
        'forma'
    ];

    /**
     * The attributes that should be casted to native types.
     *
     * @var array
     */
    protected $casts = [
        'id' => 'integer',
        'forma' => 'string'
    ];

    /**
     * Validation rules
     *
     * @var array
     */
    public static $rules = [
        'forma' => 'required'
    ];

    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     **/
    public function pensions()
    {
        return $this->hasMany(\App\Models\Pension::class, 'id_forma_pago');
    }
}

app/Http/Controllers/FormaPagoController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\CreateFormaPagoRequest;
use App\Http\Requests\UpdateFormaPagoRequest;
use App\Repositories\FormaPagoRepository;
use App\Http\Controllers\AppBaseController;
use Illuminate\Http\Request;
use Flash;
use Response;

class FormaPagoController extends AppBaseController
{
    /** @var  FormaPagoRepository */
    private $formaPagoRepository;

    public function __construct(FormaPagoRepository $formaPagoRepo)
    {
        $this->formaPagoRepository = $formaPagoRepo;
    }

    /**
     * Display a listing of the FormaPago.
     *
     * @param Request $request
     *
     * @return Response
     */
    public function index(Request $request)
    {
        $formaPagos = $this->formaPagoRepository->all();

        return view('forma_pagos.index')
            ->with('formaPagos', $formaPagos);
    }

    /**
     * Show the form for creating a new FormaPago.
     *
     * @return Response
     */
    public function create()
    {
        return view('forma_pagos.create');
    }

    /**
     * Store a newly created FormaPago in storage.
     *
     * @param CreateFormaPagoRequest $request
     *
     * @return Response
     */
    public function store(CreateFormaPagoRequest $request)
    {
        $input = $request->all();

        $formaPago = $this->formaPagoRepository->create($input);

        Flash::success('Forma Pago saved successfully.');

        return redirect(route('formaPagos.index'));
    }

    /**
     * Display the specified FormaPago.
     *
     * @param int $id
     *
     * @return Response
     */
    public function show($id)
    {
        $formaPago = $this->formaPagoRepository->find($id);

        if (empty($formaPago)) {
            Flash::error('Forma Pago not found');

            return redirect(route('formaPagos.index'));
        }

        return view('forma_pagos.show')->with('formaPago', $formaPago);
    }

    /**
     * Show the form for editing the specified FormaPago.
     *
     * @param int $id
     *
     * @return Response
     */
    public function edit($id)
    {
        $formaPago = $this->formaPagoRepository->find($id);

        if (empty($formaPago)) {
            Flash::error('Forma Pago not found');

            return redirect(route('formaPagos.index'));
        }

        return view('forma_pagos.edit')->with('formaPago', $formaPago);
    }

    /**
     * Update the specified FormaPago in storage.
     *
     * @param int $id
     * @param UpdateFormaPagoRequest $request
     *
     * @return Response
     */
    public function update($id, UpdateFormaPagoRequest $request)
    {
        $formaPago = $this->formaPagoRepository->find($id);

        if (empty($formaPago)) {
            Flash::error('Forma Pago not found');

            return redirect(route('formaPagos.index'));
        }

        $formaPago = $this->formaPagoRepository->update($request->all(), $id);

        Flash::success('Forma Pago updated successfully.');

        return redirect(route('formaPagos.index'));
    }

    /**
     * Remove the specified FormaPago from storage.
     *
     * @param int $id
     *
     * @throws \Exception
     *
     * @return Response
     */
    public function destroy($id)
    {
        $formaPago = $this->formaPagoRepository->find($id);

        if (empty($formaPago)) {
            Flash::error('Forma Pago not found');

            return redirect(route('formaPagos.index'));
        }

        $this->formaPagoRepository->delete($id);

        Flash::success('Forma Pago deleted successfully.');

        return redirect(route('formaPagos.index'));
    }
}

resources/views/forma_pagos/create.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Forma Pago
        </h1>
    </section>
    <div class="content">
        @include('adminlte-templates::common.errors')
        <div class="box box-primary">

            <div class="box-body">
                <div class="row">
                    {!! Form::open(['route' => 'formaPagos.store']) !!}

                        @include('forma_pagos.fields')

                    {!! Form::close() !!}
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/forma_pagos/edit.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Forma Pago
        </h1>
   </section>
   <div class="content">
       @include('adminlte-templates::common.errors')
       <div class="box box-primary">
           <div class="box-body">
               <div class="row">
                   {!! Form::model($formaPago, ['route' => ['formaPagos.update', $formaPago->id], 'method' => 'patch']) !!}

                        @include('forma_pagos.fields')

                   {!! Form::close() !!}
               </div>
           </div>
       </div>
   </div>
@endsection

resources/views/forma_pagos/fields.blade.php
<!-- Forma Field -->
<div class="form-group col-sm-6">
    {!! Form::label('forma', 'Forma:') !!}
    {!! Form::text('forma', null, ['class' => 'form-control']) !!}
</div>

<!-- Submit Field -->
<div class="form-group col-sm-12">
    {!! Form::submit('Save', ['class' => 'btn btn-primary']) !!}
    <a href="{!! route('formaPagos.index') !!}" class="btn btn-default">Cancel</a>
</div>

resources/views/forma_pagos/index.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1 class="pull-left">Forma Pagos</h1>
        <h1 class="pull-right">
           <a class="btn btn-primary pull-right" style="margin-top: -10px;margin-bottom: 5px" href="{!! route('formaPagos.create') !!}">Add New</a>
        </h1>
    </section>
    <div class="content">
        <div class="clearfix"></div>

        @include('flash::message')

        <div class="clearfix"></div>
        <div class="box box-primary">
            <div class="box-body">
                    @include('forma_pagos.table')
            </div>
        </div>
        <div class="text-center">
        
        </div>
    </div>
@endsection

resources/views/forma_pagos/show.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Forma Pago
        </h1>
    </section>
    <div class="content">
        <div class="box box-primary">
            <div class="box-body">
                <div class="row" style="padding-left: 20px">
                    @include('forma_pagos.show_fields')
                    <a href="{!! route('formaPagos.index') !!}" class="btn btn-default">Back</a>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/forma_pagos/show_fields.blade.php
<!-- Id Field -->
<div class="form-group">
    {!! Form::label('id', 'Id:') !!}
    <p>{!! $formaPago->id !!}</p>
</div>

<!-- Forma Field -->
<div class="form-group">
    {!! Form::label('forma', 'Forma:') !!}
    <p>{!! $formaPago->forma !!}</p>
</div>

<!-- Created At Field -->
<div class="form-group">
    {!! Form::label('created_at', 'Created At:') !!}
    <p>{!! $formaPago->created_at !!}</p>
</div>

<!-- Updated At Field -->
<div class="form-group">
    {!! Form::label('updated_at', 'Updated At:') !!}
    <p>{!! $formaPago->updated_at !!}</p>
</div>

resources/views/forma_pagos/table.blade.php
<div class="table-responsive">
    <table class="table" id="formaPagos-table">
        <thead>
            <tr>
                <th>Forma</th>
                <th colspan="3">Action</th>
            </tr>
        </thead>
        <tbody>
        @foreach($formaPagos as $formaPago)
            <tr>
                <td>{!! $formaPago->forma !!}</td>
                <td>
                    {!! Form::open(['route' => ['formaPagos.destroy', $formaPago->id], 'method' => 'delete']) !!}
                    <div class='btn-group'>
                        <a href="{!! route('formaPagos.show', [$formaPago->id]) !!}" class='btn btn-default btn-xs'><i class="glyphicon glyphicon-eye-open"></i></a>
                        <a href="{!! route('formaPagos.edit', [$formaPago->id]) !!}" class='btn btn-default btn-xs'><i class="glyphicon glyphicon-edit"></i></a>
                        {!! Form::button('<i class="glyphicon glyphicon-trash"></i>', ['type' => 'submit', 'class' => 'btn btn-danger btn-xs', 'onclick' => "return confirm('Are you sure?')"]) !!}
                    </div>
                    {!! Form::close() !!}
                </td>
            </tr>
        @endforeach
        </tbody>
    </table>
</div>