routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'Auth\LoginController@showLoginForm');
Auth::Routes();
Route::group(['middleware' => 'auth'], function () {
    Route::get('/home', 'HomeController@index')->name('home');
    Route::resource('clientes', 'ClienteController');
    Route::resource('infoClientes', 'InfoClienteController');
    Route::resource('central_users', 'CentralUserController');
    Route::resource('logs', 'LogController');
    Route::resource('permisos', 'PermisoController');
    Route::resource('roles', 'RolesController');
    Route::resource('marcas', 'MarcasController');
    Route::resource('orgs', 'OrgController');
    Route::resource('estacionamientos', 'EstacionamientoController');
    Route::resource('tipoTickets', 'TipoTicketController');
    Route::resource('tickets', 'TicketController');
    Route::resource('factura', 'FacturaController');
    Route::resource('tipoPagos', 'TipoPagoController');
    Route::resource('tipoPensions', 'TipoPensionController');
    Route::resource('formaPagos', 'FormaPagoController');
    Route::resource('imgIngresos', 'ImgIngresoController');
    Route::resource('ingresos', 'IngresoController');
    Route::resource('bancoCollects', 'BancoCollectController');
    Route::resource('empresaCollects', 'EmpresaCollectController');
    Route::resource('gerentes', 'GerenteController');
    Route::resource('dashboard', 'DashboardController');
    Route::resource('diarioingreso', 'DiarioIngresoController');
    Route::resource('firmas', 'FirmaController');
    Route::get('/xml/{id}', 'FacturaController@downloadXML')->name('xml');
    Route::get('/pdf/{id}', 'FacturaController@downloadPDF')->name('pdf');
    Route::get('/img/{id}', 'TicketController@DownImg')->name('img');
    Route::post('/generar/', 'FacturaController@create')->name('generar');
    Route::post('/buscar/facturas','FacturaController@busqueda')->name('busqueda');
    Route::post('/email', 'FacturaController@enviarEmail')->name('email');
    Route::post('/actualiza/{id}', 'TicketController@actualiza')->name('no_est');
    Route::post('/tickets/timbrado/', 'FacturaController@timbrado')->name('timbrar');
    Route::get('/tickets/validar/{id}', 'TicketController@valido')->name('valido');
    Route::post('/tickets/rechazo/{id}', 'TicketController@rechazo')->name('rechazo');
    Route::get('/rechazados', 'TicketController@list_rechazo')->name('list_rechazo');
    Route::post('dashboard', 'DashboardController@AjaxRequest')->name('dashboard');
    Route::get('/graficas/{id}', 'EstacionamientoController@graficas')->name('graficas');
    Route::get('/ingresos/rechazados', 'IngresoController@Frechazos')->name('ingresos.rechazo');
    Route::get('/facturas/pi','FacturaController@pi')->name('pi');
    Route::get('/orgs/cambio/{id}','OrgController@cambio')->name('cambio');
    Route::get('/fichas/validar/{id}', 'IngresoController@Fvalidos')->name('valido_ficha');
    Route::post('/fichas/rechazo/{id}', 'IngresoController@Frechazos')->name('rechazo_ficha');
    Route::get('/calendario','IngresoController@calendario')->name('calendar');
});



Route::resource('pagos', 'PagoController');
Route::resource('operacionDiarias', 'OperacionDiariaController');
Route::resource('pensions', 'PensionController');


Route::resource('operacionDiarias', 'OperacionDiariaController');

Route::resource('facturaPensions', 'FacturaPensionController');

app/Models/TipoPension.php
<?php

namespace App\Models;

use Eloquent as Model;
use Illuminate\Database\Eloquent\SoftDeletes;

/**
 * Class TipoPension
 * @package App\Models
 * @version September 19, 2019, 5:20 pm UTC
 *
 * @property \Illuminate\Database\Eloquent\Collection pensions
 * @property string tipo
 */
class TipoPension extends Model
{
    use SoftDeletes;

    public $table = 'tipo_pen';
    
    const CREATED_AT = 'created_at';
    const UPDATED_AT = 'updated_at';


    protected $dates = ['deleted_at'];


    public $fillable = [
        'tipo'
    ];

    /**
     * The attributes that should be casted to native types.
     *
     * @var array
     */
    protected $casts = [
        'id' => 'integer',
        'tipo' => 'string'
    ];

    /**
     * Validation rules
     *
     * @var array
     */
    public static $rules = [
        'tipo' => 'required'
    ];

    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     **/
    public function pensions()
    {
        return $this->hasMany(\App\Models\Pension::class, 'id_tipo_pen');
    }
}

app/Http/Controllers/TipoPensionController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\CreateTipoPensionRequest;
use App\Http\Requests\UpdateTipoPensionRequest;
use App\Repositories\TipoPensionRepository;
use App\Http\Controllers\AppBaseController;
use Illuminate\Http\Request;
use Flash;
use Response;

class TipoPensionController extends AppBaseController
{
    /** @var  TipoPensionRepository */
    private $tipoPensionRepository;

    public function __construct(TipoPensionRepository $tipoPensionRepo)
    {
        $this->tipoPensionRepository = $tipoPensionRepo;
    }

    /**
     * Display a listing of the TipoPension.
     *
     * @param Request $request
     *
     * @return Response
     */
    public function index(Request $request)
    {
        $tipoPensions = $this->tipoPensionRepository->all();

        return view('tipo_pensions.index')
            ->with('tipoPensions', $tipoPensions);
    }

    /**
     * Show the form for creating a new TipoPension.
     *
     * @return Response
     */
    public function create()
    {
        return view('tipo_pensions.create');
    }

    /**
     * Store a newly created TipoPension in storage.
     *
     * @param CreateTipoPensionRequest $request
     *
     * @return Response
     */
    public function store(CreateTipoPensionRequest $request)
    {
        $input = $request->all();

        $tipoPension = $this->tipoPensionRepository->create($input);

        Flash::success('Tipo Pension saved successfully.');

        return redirect(route('tipoPensions.index'));
    }

    /**
     * Display the specified TipoPension.
     *
     * @param int $id
     *
     * @return Response
     */
    public function show($id)
    {
        $tipoPension = $this->tipoPensionRepository->find($id);

        if (empty($tipoPension)) {
            Flash::error('Tipo Pension not found');

            return redirect(route('tipoPensions.index'));
        }

        return view('tipo_pensions.show')->with('tipoPension', $tipoPension);
    }

    /**
     * Show the form for editing the specified TipoPension.
     *
     * @param int $id
     *
     * @return Response
     */
    public function edit($id)
    {
        $tipoPension = $this->tipoPensionRepository->find($id);

        if (empty($tipoPension)) {
            Flash::error('Tipo Pension not found');

            return redirect(route('tipoPensions.index'));
        }

        return view('tipo_pensions.edit')->with('tipoPension', $tipoPension);
    }

    /**
     * Update the specified TipoPension in storage.
     *
     * @param int $id
     * @param UpdateTipoPensionRequest $request
     *
     * @return Response
     */
    public function update($id, UpdateTipoPensionRequest $request)
    {
        $tipoPension = $this->tipoPensionRepository->find($id);

        if (empty($tipoPension)) {
            Flash::error('Tipo Pension not found');

            return redirect(route('tipoPensions.index'));
        }

        $tipoPension = $this->tipoPensionRepository->update($request->all(), $id);

        Flash::success('Tipo Pension updated successfully.');

        return redirect(route('tipoPensions.index'));
    }

    /**
     * Remove the specified TipoPension from storage.
     *
     * @param int $id
     *
     * @throws \Exception
     *
     * @return Response
     */
    public function destroy($id)
    {
        $tipoPension = $this->tipoPensionRepository->find($id);

        if (empty($tipoPension)) {
            Flash::error('Tipo Pension not found');

            return redirect(route('tipoPensions.index'));
        }

        $this->tipoPensionRepository->delete($id);

        Flash::success('Tipo Pension deleted successfully.');

        return redirect(route('tipoPensions.index'));
    }
}

resources/views/tipo_pensions/create.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Tipo Pension
        </h1>
    </section>
    <div class="content">
        @include('adminlte-templates::common.errors')
        <div class="box box-primary">

            <div class="box-body">
                <div class="row">
                    {!! Form::open(['route' => 'tipoPensions.store']) !!}

                        @include('tipo_pensions.fields')

                    {!! Form::close() !!}
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/tipo_pensions/edit.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Tipo Pension
        </h1>
   </section>
   <div class="content">
       @include('adminlte-templates::common.errors')
       <div class="box box-primary">
           <div class="box-body">
               <div class="row">
                   {!! Form::model($tipoPension, ['route' => ['tipoPensions.update', $tipoPension->id], 'method' => 'patch']) !!}

                        @include('tipo_pensions.fields')

                   {!! Form::close() !!}
               </div>
           </div>
       </div>
   </div>
@endsection

resources/views/tipo_pensions/fields.blade.php
<!-- Tipo Field -->
<div class="form-group col-sm-6">
    {!! Form::label('tipo', 'Tipo:') !!}
    {!! Form::text('tipo', null, ['class' => 'form-control']) !!}
</div>

<!-- Submit Field -->
<div class="form-group col-sm-12">
    {!! Form::submit('Save', ['class' => 'btn btn-primary']) !!}
    <a href="{!! route('tipoPensions.index') !!}" class="btn btn-default">Cancel</a>
</div>

resources/views/tipo_pensions/index.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1 class="pull-left">Tipo Pensions</h1>
        <h1 class="pull-right">
           <a class="btn btn-primary pull-right" style="margin-top: -10px;margin-bottom: 5px" href="{!! route('tipoPensions.create') !!}">Add New</a>
        </h1>
    </section>
    <div class="content">
        <div class="clearfix"></div>

        @include('flash::message')

        <div class="clearfix"></div>
        <div class="box box-primary">
            <div class="box-body">
                    @include('tipo_pensions.table')
            </div>
        </div>
        <div class="text-center">
        
        </div>
    </div>
@endsection

resources/views/tipo_pensions/show.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Tipo Pension
        </h1>
    </section>
    <div class="content">
        <div class="box box-primary">
            <div class="box-body">
                <div class="row" style="padding-left: 20px">
                    @include('tipo_pensions.show_fields')
                    <a href="{!! route('tipoPensions.index') !!}" class="btn btn-default">Back</a>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/tipo_pensions/show_fields.blade.php
<!-- Id Field -->
<div class="form-group">
    {!! Form::label('id', 'Id:') !!}
    <p>{!! $tipoPension->id !!}</p>
</div>

<!-- Tipo Field -->
<div class="form-group">
    {!! Form::label('tipo', 'Tipo:') !!}
    <p>{!! $tipoPension->tipo !!}</p>
</div>

<!-- Created At Field -->
<div class="form-group">
    {!! Form::label('created_at', 'Created At:') !!}
    <p>{!! $tipoPension->created_at !!}</p>
</div>

<!-- Updated At Field -->
<div class="form-group">
    {!! Form::label('updated_at', 'Updated At:') !!}
    <p>{!! $tipoPension->updated_at !!}</p>
</div>

resources/views/tipo_pensions/table.blade.php
<div class="table-responsive">
    <table class="table" id="tipoPensions-table">
        <thead>
            <tr>
                <th>Tipo</th>
                <th colspan="3">Action</th>
            </tr>
        </thead>
        <tbody>
        @foreach($tipoPensions as $tipoPension)
            <tr>
                <td>{!! $tipoPension->tipo !!}</td>
                <td>
                    {!! Form::open(['route' => ['tipoPensions.destroy', $tipoPension->id], 'method' => 'delete']) !!}
                    <div class='btn-group'>
                        <a href="{!! route('tipoPensions.show', [$tipoPension->id]) !!}" class='btn btn-default btn-xs'><i class="glyphicon glyphicon-eye-open"></i></a>
                        <a href="{!! route('tipoPensions.edit', [$tipoPension->id]) !!}" class='btn btn-default btn-xs'><i class="glyphicon glyphicon-edit"></i></a>
                        {!! Form::button('<i class="glyphicon glyphicon-trash"></i>', ['type' => 'submit', 'class' => 'btn btn-danger btn-xs', 'onclick' => "return confirm('Are you sure?')"]) !!}
                    </div>
                    {!! Form::close() !!}
                </td>
            </tr>
        @endforeach
        </tbody>
    </table>
</div>